title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

twitter_username: jekyllrb
github_username:  jekyll

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

prose:
  rooturl: '_posts'
  media: 'images'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Enter your title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "article"
      - name: "author"
        field:
          element: "text"
          label: 'Author'
          placeholder: "post author"
      - name: "image_teaser"
        field:
          element: "text"
          value: "https://media3.giphy.com/media/3og0IFRM2W3Ylg4tIA/giphy.gif"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish?"
          help: "Check the box when ready to publish"
          value: false
      - name: "modified"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
          
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
